from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from datetime import datetime
import logging

from app.models.sku import SKU
from app.models.price_decision import PriceDecision

from app.services.feature_service import FeatureService
from app.services.ml_model import DemandModelService
from app.services.price_optimizer import PriceOptimizer
from app.services.pricing_engine import PricingEngine
from app.services.pricing_rl_agent import PricingRLAgent


logger = logging.getLogger(__name__)


class AutoPricingAgent:

    # =====================================================
    # Run pricing for all SKUs of a tenant
    # =====================================================
    @staticmethod
    async def run_for_tenant(
        db: AsyncSession,
        tenant_id: int,
        objective: str = "profit"
    ):
        """
        Runs pricing for all SKUs of a tenant
        """

        result = await db.execute(
            select(SKU).where(SKU.tenant_id == tenant_id)
        )
        skus = result.scalars().all()

        decisions = []

        for sku in skus:
            try:
                decision = await AutoPricingAgent._process_single_sku(
                    db=db,
                    tenant_id=tenant_id,
                    sku=sku,
                    objective=objective
                )
                decisions.append(decision)

            except Exception as e:
                logger.error(f"[AUTO PRICING ERROR] SKU {sku.id}: {str(e)}")

                decisions.append({
                    "sku_id": sku.id,
                    "error": str(e)
                })

        return {
            "tenant_id": tenant_id,
            "processed": len(decisions),
            "decisions": decisions
        }

    # =====================================================
    # Process One SKU
    # =====================================================
    @staticmethod
    async def _process_single_sku(
        db: AsyncSession,
        tenant_id: int,
        sku,
        objective: str
    ):
        """
        End-to-end pricing pipeline for one SKU
        """

        # 1️⃣ Fetch features
        features = await FeatureService.get_features(
            db=db,
            sku_id=sku.id,
            tenant_id=tenant_id
        )

        # Safe feature extraction
        avg_comp = features.get("avg_competitor_price", 0)
        min_comp = features.get("min_competitor_price", 0)
        max_comp = features.get("max_competitor_price", 0)

        # 2️⃣ Predict demand
        predicted_demand = DemandModelService.predict(
            tenant_id,
            features
        )

        # 3️⃣ Optimize candidate prices
        cost_price = float(sku.cost_price or 0)
        base_price = float(sku.base_price or 0)

        optimization = PriceOptimizer.optimize_price(
            tenant_id=tenant_id,
            cost_price=cost_price,
            base_price=base_price,
            features=features,
            objective=objective
        )

        candidate_prices = optimization.get("price_candidates", [])

        if not candidate_prices:
            raise Exception("No candidate prices generated by optimizer")

        # 4️⃣ RL chooses best price
        chosen_price = await PricingRLAgent.choose_price(
            db=db,
            tenant_id=tenant_id,
            sku_id=sku.id,
            candidate_prices=candidate_prices
        )

        # 5️⃣ Apply pricing safety rules
        pricing = PricingEngine.calculate_price(
            cost_price=cost_price,
            base_price=float(chosen_price),
            predicted_demand=predicted_demand,
            avg_comp_price=avg_comp,
            min_comp_price=min_comp,
            max_comp_price=max_comp,
        )

        final_price = pricing["recommended_price"]

        # 6️⃣ Save decision
        decision = PriceDecision(
            tenant_id=tenant_id,
            sku_id=sku.id,
            recommended_price=final_price,
            base_price=base_price,
            cost_price=cost_price,
            predicted_demand=predicted_demand,
            strategy="auto-optimized",
            reason=f"{objective}-optimized via ML + rules",
            model_version="v1",
            created_at=datetime.utcnow()
        )

        try:
            db.add(decision)
            await db.commit()
        except Exception as e:
            await db.rollback()
            logger.error(f"[DB ERROR] SKU {sku.id}: {str(e)}")
            raise e

        logger.info(
            f"[AUTO PRICING] SKU {sku.id} | Final Price: {final_price} | Demand: {predicted_demand}"
        )

        return {
            "sku_id": sku.id,
            "recommended_price": final_price,
            "predicted_demand": predicted_demand,
            "objective": objective
        }