
services:

  postgres:
    image: postgres:15
    container_name: pricing_postgres
    environment:
      POSTGRES_USER: pricing_user
      POSTGRES_PASSWORD: pricing_pass
      POSTGRES_DB: pricing_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: pricing_prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: pricing_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  pgdata: