"""create competitor_prices table

Revision ID: 278e1a0e587e
Revises: a0f21b31e8ac
Create Date: 2026-02-13 10:48:36.432673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278e1a0e587e'
down_revision: Union[str, Sequence[str], None] = 'a0f21b31e8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('competitor_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_prices_captured_at'), 'competitor_prices', ['captured_at'], unique=False)
    op.create_index(op.f('ix_competitor_prices_sku_id'), 'competitor_prices', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_prices_sku_id'), table_name='competitor_prices')
    op.drop_index(op.f('ix_competitor_prices_captured_at'), table_name='competitor_prices')
    op.drop_table('competitor_prices')
    # ### end Alembic commands ###
