"""create demand_signals table

Revision ID: 51942fc81f09
Revises: 278e1a0e587e
Create Date: 2026-02-13 11:05:34.925355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51942fc81f09'
down_revision: Union[str, Sequence[str], None] = '278e1a0e587e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_signals_captured_at'), 'demand_signals', ['captured_at'], unique=False)
    op.create_index(op.f('ix_demand_signals_signal_type'), 'demand_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_demand_signals_sku_id'), 'demand_signals', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demand_signals_sku_id'), table_name='demand_signals')
    op.drop_index(op.f('ix_demand_signals_signal_type'), table_name='demand_signals')
    op.drop_index(op.f('ix_demand_signals_captured_at'), table_name='demand_signals')
    op.drop_table('demand_signals')
    # ### end Alembic commands ###
