"""create price_decisions table

Revision ID: c6767d5634e2
Revises: 51942fc81f09
Create Date: 2026-02-13 11:23:20.671439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6767d5634e2'
down_revision: Union[str, Sequence[str], None] = '51942fc81f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('recommended_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_decisions_created_at'), 'price_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_decisions_sku_id'), 'price_decisions', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_decisions_sku_id'), table_name='price_decisions')
    op.drop_index(op.f('ix_price_decisions_created_at'), table_name='price_decisions')
    op.drop_table('price_decisions')
    # ### end Alembic commands ###
